### ISSUE TITLE
希望能内建支持ssh方式连接到服务器

### ISSUE THREAD

**Issue by maq128** [sower-proxy/sower#21]
在知道sower之前，我上网使用代理的方式是这样的：用ssh登录到境外服务器（已购买了境外的云服务器），这样就建立了本地的SOCKS5代理服务，然后使用“Chrome浏览器+SwitchyOmega+SOCKS5”。

这种方式基本上解决了所有网页浏览的问题，但还有一些场景无法覆盖，比如用npm安装过程中需要从github下载程序包。虽然npm本身可以配置使用代理，但第三方包安装过程中可能会用到其它的下载方式，比如wget/curl之类，而且有些只支持HTTP代理，不支持SOCKS5代理，所以每次遇到这种情况都很狼狈。

sower用了一下，果然是神器！

我现在的用法是：没有在服务器端安装sowerd，而是在sower客户端配置为使用我已有的SOCKS5代理服务。

这种方式现在已经可以很好地工作了。于是我想，这可能是一种比较典型的使用模式吧？如果有条件安装服务器端sowerd，那大概率也是可以直接用ssh登录境外服务器的，那么如果sower能够直接通过ssh连接到服务器作为内建的SOCKS5代理，使用起来就会更简单一点了。

**Comment by wweir** [comment]
多谢抬爱，网络代理要解决的一个很重要的问题是：把本地的访问流量代理到远程，且不会因为产生太多特征流量被识别。

伪装得尽量像正常的网络访问，是一个很重要的方式，也就是常说的混淆。

ssh 的方式进行流量代理本身是技术上没有问题的。但一旦以这种方式直接走公网流向国外，会因为流量的特征太过明显，被迅速识别，进而连带屏蔽整个境外服务器。

所以，这个功能做是可以做的，但做出来很难解决实际的问题。

这里我就先关闭了，如果有什么能够带来便携的场景，欢迎再提。

ps: 看了你的代码，挺好的，加油 👍

**Comment by maq128** [comment]
多谢回复。理解。
说到流量特征被识别的问题，这个问题肯定是存在的，不过从我个人的实际使用效果来看，似乎影响并不大。也许因为只是个人使用，流量本身就不大，并不招人耳目。
我自己尝试增加了这个功能，感觉还是挺实用的。源代码结构设计很清楚，所以增加这个功能也比较容易，我没有花太多精力打磨，只是给自己用嘛，够用就好。
现在对 sower 已经很依赖了，尤其是在使用 wsl 和 docker 的时候，以前安装一个程序库需要各种设置代理参数轮番上（git, curl, npm, ...），现在只要开启 sower 直接搞定！
感谢！
