### ISSUE TITLE
建议域名的通配符可以匹配“空”

### ISSUE THREAD

**Issue by maq128** [sower-proxy/sower#22]
比如 `*.github.com`，按照目前的匹配逻辑，可以匹配 `www.github.com`，但是却不能匹配 `github.com`，然而多数情况下这种匹配是需要的，为此我不得不另外再写一条规则。如果 `*.` 能够匹配到“空”的话就比较方便了。

**Comment by wweir** [comment]
不好意思，年前公司事情太多，看漏了通知邮件了，才看到这个问题。
这个场景的支持是很有意义的，马上改下

**Comment by wweir** [comment]
最新版本已支持，不过得 `**.` 的前缀才支持
