### ISSUE TITLE
为什么要dhcp获取dns server

### ISSUE THREAD

**Issue by fbion** [sower-proxy/sower#23]
可以手动设置吗

**Comment by wweir** [comment]
不好意思，最近被隔离得有点魔怔了，才看到问题。

支持 DHCP 的原因是：
- 部分公开访问的 WI-FI，会首先跳转到一个认证页面，进行认证后才能访问，常见于宾馆、酒店、一些商场店面之类的场所
- 这个过程，需要使用 DHCP 中规定的 DNS 才能完成
- 这个功能主要对笔记本之类的移动设备很有帮助
  - 之前有次去 Genius Bar 修电脑，一直连不上 WI-FI，就很尴尬

**Comment by wweir** [comment]
手动设置只需要设置那个 `dns.fallback` 就可以了。

不过没提供只使用自定义 DNS 的功能，主要是没找到一个一定要这么做，才能正常工作的场景
