### ISSUE TITLE
将 Sower 部署在局域网内，Windows 设备不可用，macOS 及 iOS 设备没有问题

### ISSUE THREAD

**Issue by imgk** [sower-proxy/sower#25]
你好，感谢提供这个好用的工具。

现在，我准备把 Sower 部属在内网上，通过 WireGuard 设置 DNS 使用，但目前 Windows 没办法正常使用，iPhone 及 mac 没有问题。

内网 IP: 192.168.0.3
Windows 版本：Windows 11 22H2

在 Windows 上的表现，nslookup 可以看到返回 google.com 的地址为 192.168.0.3，但无法连接，curl 也连不上。

把 Sower 部属在本机上则没有问题。

请问有遇到过类似问题吗？

Update:
![image](https://user-images.githubusercontent.com/14073640/201082289-aa76d713-706a-4f84-a78c-35ebffdccf5d.png)

为什么 nslookup 和 curl 使用的 IP 不一致呢？

使用本机地址则没有问题
![image](https://user-images.githubusercontent.com/14073640/201083607-f06be274-4f68-4f15-95a1-3c6a0a32fa75.png)

**Comment by wweir** [comment]
感谢认可！

之前 0.* 版本的时候，尝试过自动更新操作系统的 DNS。里面遇到个问题，就是变更完之后，需要执行 flush 命令，才能让这个 DNS 生效。不知道你这边遇到的，是不是这个问题，可以尝试一下。
macOS: 
```shell
pkill mDNSResponder || true
```
Windows: 
```powershell
ipconfig /flushdnss
```

**Comment by imgk** [comment]
然而并没有用，算了吧
